### ISSUE TITLE
setState test

### ISSUE THREAD

**Issue by NamJwong** [NamJwong/react-practice#10]
<img width="949" alt="image" src="https://user-images.githubusercontent.com/73823388/199187333-c881e6ce-e389-4ed6-8626-ab0ae9add050.png">

[React 공식 문서의 위 내용](https://ko.reactjs.org/docs/forms.html#handling-multiple-inputs)이 함수형 컴포넌트에서도 똑같이 동작하는지 테스트 해보기

### 궁금한 이유
평소에는 무조건 `setState((prev) => ({ ...prev, 속성: 값 }))` 같은 방식으로 하는 것이 좋다고 알고 있어서 이렇게 해왔다.
이유는 아마 불변성?을 위해?
그런데 사실 불변성이 뭔지도 잘 모르고 이렇게 하지 않으면 불변성이 왜 지켜지지 않는지 정확한 원리를 알지 못한다.

따라서 위 코드가 함수형 컴포넌트에서 동작하는지 확인하고, 어떤 방법이 좋은 것인지까지 알 수 있으면 좋을 것 같다.

### TODO
- [ ] 함수형 컴포넌트에서도 가능한 코드인지 테스트
- [ ] 리액트에서 불변성이란 무엇인지 알아보기
- [ ] 왜 `setState((prev) => ({ ...prev, 속성: 값 }))` 방식으로 해야 한다 배웠던 것인지 이해하기
- [ ] 좋은 setState 방식에 대한 고찰
